esphome:
  name: bedroom
  includes:
    - environment_sensor.h
  libraries:
    - "Wire"
    - "DFRobot_RTU"
    - "DFRobot_EnvironmentalSensor"

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable Home Assistant API
api:
  encryption:
    key: "0YKSscqNoZYS7AMCKVH2p9TTCxWaAynI++ZhnWm0rVY="

sensor:
  - platform: custom
    lambda: |-
      auto my_sensor = new MyCustomSensor();
      App.register_component(my_sensor);
      return {my_sensor->temperature_sensor, my_sensor->pressure_sensor, my_sensor->humidity_sensor, my_sensor->ultraviolet_sensor, my_sensor->luminous_intensity_sensor};

    sensors:
    - name: "Temperature Sensor"
      unit_of_measurement: °C
      accuracy_decimals: 1
    - name: "Pressure Sensor"
      unit_of_measurement: hPa
      accuracy_decimals: 0
    - name: "Humidity Sensor"
      unit_of_measurement: \%
      accuracy_decimals: 0
    - name: "Ultraviolet Sensor"
      unit_of_measurement: mw/cm²
      accuracy_decimals: 2
    - name: "Luminous Intensity Sensor"
      unit_of_measurement: lx
      accuracy_decimals: 2
# Enable logging
logger:

ota:
  password: "c94678a3b2419d35bbe73412341b5c9f"

wifi:
  ssid: "enterhere"
  password: "enterhere"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bedroom Fallback Hotspot"
    password: "g2T96cpW1UPi"

captive_portal:
    
